#!/usr/bin/env bash
# Installs `voice-coder` into ~/.local/bin as a small wrapper script that
# pins the absolute path of `node`. This avoids the common gotcha where
# desktop-environment keyboard-shortcut handlers run with a stripped PATH
# that resolves `node` to an ancient /usr/bin/node (e.g. Node 12 on Ubuntu)
# rather than your shell's modern Node.
#
# Idempotent. Safe to re-run after upgrading Node — it just rewrites the
# wrapper with the currently active node.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI_JS="$ROOT/out/cli.js"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
WRAPPER="$BIN_DIR/voice-coder"

if [[ ! -f "$CLI_JS" ]]; then
  echo "✗ $CLI_JS not found. Run 'pnpm run compile:cli' first." >&2
  exit 1
fi

NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]]; then
  echo "✗ 'node' not on PATH. Install Node ≥ 20 first." >&2
  exit 1
fi
# Resolve through any symlinks (nvm shim, etc.) to a stable absolute path
NODE_BIN="$(readlink -f "$NODE_BIN")"

NODE_MAJOR="$("$NODE_BIN" -p 'process.versions.node.split(".")[0]')"
if (( NODE_MAJOR < 20 )); then
  echo "✗ $NODE_BIN is Node $NODE_MAJOR — need ≥ 20. The CLI bundle uses ES2022 syntax." >&2
  exit 1
fi

mkdir -p "$BIN_DIR"

# Remove an existing symlink (legacy install) or wrapper, then write fresh
if [[ -L "$WRAPPER" || -e "$WRAPPER" ]]; then
  rm -f "$WRAPPER"
fi

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by voice-coder/scripts/install-cli.sh — re-run after upgrading Node.
exec "$NODE_BIN" "$CLI_JS" "\$@"
EOF
chmod +x "$WRAPPER"

echo "✓ Installed: $WRAPPER"
echo "  uses: $NODE_BIN (Node $NODE_MAJOR)"
echo "  runs: $CLI_JS"

if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
  echo
  echo "⚠  $BIN_DIR is not in your PATH."
  echo "   Add this to ~/.bashrc or ~/.zshrc:"
  echo "     export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo "   Then start a new shell or run: source ~/.bashrc"
fi

echo
echo "For desktop keyboard shortcuts, set the command to the absolute path:"
echo "  $WRAPPER toggle"
